### ISSUE TITLE
Intensity of wavefile is not the same from praat and parselmouth

### ISSUE THREAD

**Issue by labodezao** [YannickJadoul/Parselmouth#104]
Hi,
I am using Paselmouth for making a lot of analysis to make R&D reasearch for improving my knowledge of accordion design.

I recorded this sound (attached in the zip file), and when I ask python to load the file with scipy.io.wavfile.read,
and make : 
```
rate,soundWave=read(path+name+ ".wav", )
sound = parselmouth.Sound(soundWave)
print(sound.get_intensity())
```
I get more than 257 dB !
wheras in praat I get 68 dB

![image](https://github.com/YannickJadoul/Parselmouth/assets/48204601/c54d2742-254f-4a72-be08-8257197815e6)
 

Do you know what could be the problem ?

[PPos0Sec0PPlus4iClap7.zip](https://github.com/YannickJadoul/Parselmouth/files/12658166/PPos0Sec0PPlus4iClap7.zip)

**Comment by YannickJadoul** [comment]
Well yeah, by 2^31, then (2147483648, as listed [here](https://docs.scipy.org/doc/scipy/reference/generated/scipy.io.wavfile.read.html))

Or use other slightly higher-level libraries like [librosa](https://librosa.org/doc/latest/generated/librosa.load.html#librosa.load) or [SoundFile](https://pysoundfile.readthedocs.io/en/latest/) where you can specify the format you want.
Or just load it in with Parselmouth. Any reason that just doing `parselmouth.Sound(file_name)` does not work for you?

**Comment by YannickJadoul** [comment]
I will close this issue meanwhile, since it's resolved
