### ISSUE TITLE
Numpy v2 incompatibility

### ISSUE THREAD

**Issue by tikuma-lsuhsc** [YannickJadoul/Parselmouth#125]
While Parselmouth does run with the just released numpy 2, it's output may be faulty.

For example,

```python
>>> ...
>>>sound = pm.Sound(x, fs)
>>>pitch = sound.to_pitch_ac(time_step=0.001)
>>>pitch.ts()[:9]
```

prints

```
'[1.126 1.126 1.126 1.126 1.126 1.126 1.126 1.126 1.126]'
```

rather than expected

```
'[0.015 0.016 0.017 0.018 0.019 0.02  0.021 0.022 0.023]'
```

## Current Workaround 

Downgrade numpy by pinning it the last release

```
pip install -U 'numpy<2'
```

**Comment by YannickJadoul** [comment]
Thanks so much, @hokiedsp! Fixed in 0.4.4, with the fix from pybind11 backported: https://github.com/YannickJadoul/Parselmouth/releases/tag/v0.4.4
