### ISSUE TITLE
praat-parselmouse seems to not be supported on linux

### ISSUE THREAD

**Issue by 123wimin321** [YannickJadoul/Parselmouth#128]
Pro:Running the same code on Linux and Windows to extract waveform and baseband diagrams from the same audio works fine on Windows, but there is a problem on Linux.

The code is as follows：
import parselmouth
import matplotlib.pyplot as plt
import uuid

audio_file_path = "audio_00f85bb0-c86c-4b22-b0c4-28f7349e3814.mp3"  # Can be replaced with any useful audio(the audio used was no problem)

# Load the sound and TextGrid using parselmouth
snd = parselmouth.Sound(audio_file_path)
audio_length = snd.get_total_duration()

# Create a figure with two subplots
fig, (ax1, ax2) = plt.subplots(2, 1, figsize=(10, 6))

# Plot the waveform
ax1.plot(snd.xs(), snd.values.T, lw=0.5, color='black')  
ax1.set_xlim([0, audio_length])
ax1.set_xlabel("Time [s]")
ax1.set_ylabel("Amplitude")
ax1.set_title("Waveform and Pitch")

# Plot the pitch contour
pitch = snd.to_pitch()
ax2.plot(pitch.xs(), pitch.selected_array['frequency'], 'o', markersize=2, label='Pitch', color='blue')
ax2.set_xlim([0, audio_length])
ax2.set_xlabel("Time [s]")
ax2.set_ylabel("Frequency [Hz]")
ax2.grid(True)

waveform_img = f"waveform_{uuid.uuid4()}.png"

plt.savefig(waveform_img) 
plt.close()

output on linux:
snd.xs(): [2.80490625 2.80490625 2.80490625 ... 2.80490625 2.80490625 2.80490625]
pitch.xs() [2.78246875 2.78246875 2.78246875 2.78246875 2.78246875 2.78246875
 2.78246875 2.78246875 2.78246875 2.78246875 2.78246875 2.78246875
 2.78246875 2.78246875 2.78246875 2.78246875 2.78246875 2.78246875
 2.78246875 2.78246875 2.78246875 2.78246875 2.78246875 2.78246875
 2.78246875 2.78246875 2.78246875 2.78246875 2.78246875 2.78246875
 2.78246875 2.78246875 2.78246875 2.78246875 2.78246875 2.78246875
 2.78246875 2.78246875 2.78246875 2.78246875 2.78246875 2.78246875
 2.78246875 2.78246875 2.78246875 2.78246875 2.78246875 2.78246875
 2.78246875 2.78246875 2.78246875 2.78246875 2.78246875 2.78246875
 2.78246875 2.78246875 2.78246875 2.78246875 2.78246875 2.78246875
 2.78246875 2.78246875 2.78246875 2.78246875 2.78246875 2.78246875
 2.78246875 2.78246875 2.78246875 2.78246875 2.78246875 2.78246875
 2.78246875 2.78246875 2.78246875 2.78246875 2.78246875 2.78246875
 2.78246875 2.78246875 2.78246875 2.78246875 2.78246875 2.78246875
 2.78246875 2.78246875 2.78246875 2.78246875 2.78246875 2.78246875
 2.78246875 2.78246875 2.78246875 2.78246875 2.78246875 2.78246875
 2.78246875 2.78246875 2.78246875 2.78246875 2.78246875 2.78246875
 2.78246875 2.78246875 2.78246875 2.78246875 2.78246875 2.78246875
 2.78246875 2.78246875 2.78246875 2.78246875 2.78246875 2.78246875
 2.78246875 2.78246875 2.78246875 2.78246875 2.78246875 2.78246875
 2.78246875 2.78246875 2.78246875 2.78246875 2.78246875 2.78246875
 2.78246875 2.78246875 2.78246875 2.78246875 2.78246875 2.78246875
 2.78246875 2.78246875 2.78246875 2.78246875 2.78246875 2.78246875
 2.78246875 2.78246875 2.78246875 2.78246875 2.78246875 2.78246875
 2.78246875 2.78246875 2.78246875 2.78246875 2.78246875 2.78246875
 2.78246875 2.78246875 2.78246875 2.78246875 2.78246875 2.78246875
 2.78246875 2.78246875 2.78246875 2.78246875 2.78246875 2.78246875
 2.78246875 2.78246875 2.78246875 2.78246875 2.78246875 2.78246875
 2.78246875 2.78246875 2.78246875 2.78246875 2.78246875 2.78246875
 2.78246875 2.78246875 2.78246875 2.78246875 2.78246875 2.78246875
 2.78246875 2.78246875 2.78246875 2.78246875 2.78246875 2.78246875
 2.78246875 2.78246875 2.78246875 2.78246875 2.78246875 2.78246875
 2.78246875 2.78246875 2.78246875 2.78246875 2.78246875 2.78246875
 2.78246875 2.78246875 2.78246875 2.78246875 2.78246875 2.78246875
 2.78246875 2.78246875 2.78246875 2.78246875 2.78246875 2.78246875
 2.78246875 2.78246875 2.78246875 2.78246875 2.78246875 2.78246875
 2.78246875 2.78246875 2.78246875 2.78246875 2.78246875 2.78246875
 2.78246875 2.78246875 2.78246875 2.78246875 2.78246875 2.78246875
 2.78246875 2.78246875 2.78246875 2.78246875 2.78246875 2.78246875
 2.78246875 2.78246875 2.78246875 2.78246875 2.78246875 2.78246875
 2.78246875 2.78246875 2.78246875 2.78246875 2.78246875 2.78246875
 2.78246875 2.78246875 2.78246875 2.78246875 2.78246875 2.78246875
 2.78246875 2.78246875 2.78246875 2.78246875 2.78246875 2.78246875
 2.78246875 2.78246875 2.78246875 2.78246875 2.78246875 2.78246875
 2.78246875 2.78246875 2.78246875 2.78246875 2.78246875 2.78246875
 2.78246875 2.78246875 2.78246875 2.78246875 2.78246875 2.78246875
 2.78246875]

**Comment by 123wimin321** [comment]
it is good working on pycharm.

**Comment by YannickJadoul** [comment]
Hi, @123wimin321, this seems to be the known issue of Parselmouth not yet being compatible with NumPy 2! (see #125).

I'm about to release a new patch version v0.4.4, which fixes this, today or tomorrow.

While waiting for that, you can `pip install "numpy<2"`, which should fix this!

**Comment by YannickJadoul** [comment]
I just released Parselmouth 0.4.4: https://github.com/YannickJadoul/Parselmouth/releases/tag/v0.4.4
The release is also on PyPI already so if you update Parselmouth with pip, it should now be compatible with NumPy 2 and work as intended. (If that's not the case, do let me know, please!)

**Comment by YannickJadoul** [comment]
I just released Parselmouth 0.4.4: https://github.com/YannickJadoul/Parselmouth/releases/tag/v0.4.4
The release is also on PyPI already so if you update Parselmouth with pip, it should now be compatible with NumPy 2 and work as intended. (If that's not the case, do let me know, please!)

**Comment by 123wimin321** [comment]
It is already solved! Thank you for your help in time! I went on a business trip these days, and I'm sorry I only saw it today and replyed you. It is important for me. Thanks again!

**Comment by YannickJadoul** [comment]
Great to hear, thanks for confirming!
