### ISSUE TITLE
package version 0.3.2.post2

### ISSUE THREAD

**Issue by craynic** [YannickJadoul/Parselmouth#13]
I found the version in wheel meta (0.3.2) does not match the version provided on pypi (0.3.2.post2).
It may cause problems when installing with version specifications like `pip install praat_parselmouth==0.3.2`.
Hope the wheel could contain the right version (assign version="0.3.2.post2" in setup.py) or just preserve the package of version 0.3.2 on pypi.

**Comment by YannickJadoul** [comment]
@craynic Yes, I messed that up, didn't I?

I created the post-release as a solution to #9, and thought I could replace `0.3.2` by with the `0.3.2.post2` filename (since it was just a packaging issue, without any changes to the actual code), avoiding this horrible `.postN` version number to actually be seen by anyone. Turns out that's not the case :-(

The problem is that I cannot re-upload deleted files/versions to PyPI, so both your alternatives are (currently) unavailable. The best solution I can think of would be to upload 0.3.3, once I get a fix to #11 included.

Do you have any other solutions or suggestions?

**Comment by craynic** [comment]
Packaging as 0.3.3 surely works, but it seems the version is related to the C++ code, so I'm not sure if it is suitable to do so.
I have a dirty way to do it. 
- Build the wheel with your patches.
- Extract the wheel package with unzip.
- `mv praat_parselmouth-0.3.2.dist-info/ praat_parselmouth-0.3.2.post3.dist-info/`
- Edit file `METADATA`, fix version to `0.3.2.post3`.
- Package the files with zip, and rename to `praat_parselmouth-0.3.2.post3-cp37-cp37m-manylinux1_x86_64.whl`
- Upload it.
It should work, though I don't think it's a clean way.

**Comment by YannickJadoul** [comment]
Interesting; I didn't think that would work, since the hashes in `RECORD` are not the same anymore? But it seems it does work: https://test.pypi.org/project/praat-parselmouth/

**Comment by YannickJadoul** [comment]
However, this horrible title "praat-parselmouth 0.3.2.post3" is still what's holding me back of actually doing that, so I'm thinking 0.3.3 (without any 0.3.2) would still be a cleaner solution, for now.

You're right, btw, that `setup.py` parses `src/version.h` for the version number ensuring there's no unwanted inconsistencies. But I could just make a full-fletched `0.3.3` release with a fix to #11?

**Comment by craynic** [comment]
I don't know what praat is or what parselmouth is. I only want to install it for my partner.
If you are sure the version 0.3.3 would never release in upstream (or this repo relies no upstream), that should be ok.

**Comment by YannickJadoul** [comment]
@craynic You should still be able to install Parselmouth with `pip install praat-parselmouth==0.3.2.post2`, if I tested that correctly?
However, I've started backporting the necessary changes to a `stable` branch, and will hopefully soon enough be able to release 0.3.3 (if the builds on this branch are willing to actually compile on Travis, that is; *sigh*).

**Comment by craynic** [comment]
This matters in my case:

    echo 'praat-parselmouth' > requirements.txt
    pip install -r requirements.txt  # 0.3.2.post2 got installed
    pip freeze > requirements.lock  # 0.3.2 written to lock file
    pip install -r requirements.lock  # no-version error occurs

**Comment by YannickJadoul** [comment]
Right, so I finally got my backported fixes working, so [0.3.3 is in the making](https://github.com/YannickJadoul/Parselmouth/commit/95337a0332a94b77642127a5e7e5dbd9f07824e3). Sorry about the delay, but we're getting there.

**Comment by YannickJadoul** [comment]
I've just release version 0.3.3 to PyPI, after finally fixing #11. Apologies for the delay, but this version should be clean and `pip freeze`able!
