### ISSUE TITLE
 How to use each part of this open-source library?

### ISSUE THREAD

**Issue by beyondyourselfjiang** [YannickJadoul/Parselmouth#131]
How to use each part of this open-source library?

**Comment by YannickJadoul** [comment]
Please be more precise. What is the issue exactly? What have you tried and what is going wrong?
Have you read and followed the documentation? https://parselmouth.readthedocs.io/en/stable/

**Comment by beyondyourselfjiang** [comment]
Thank you for your email to help me solve the problem and give me the
documentation.
best wishes

Yannick Jadoul ***@***.***> 于2024年9月14日周六 17:10写道：
