### ISSUE TITLE
speaker diarization with parselmouth?

### ISSUE THREAD

**Issue by sivang** [YannickJadoul/Parselmouth#14]
You've mentioned to use github to communicate :)

I'd like to figure if we parselmouth can enable speaker diarization:
- based on 2 channels in a stereo recording
- out of a mono recording.

I'm happy to help and contribute to add this if not already possible.

**Comment by YannickJadoul** [comment]
Hello, @sivang. Did I (mention to use GitHub)?
Sure, why not, I suppose; though there's also [Gitter](https://gitter.im/PraatParselmouth/Lobby) of course, if you prefer; as you wish.

Anyway, about your actual question: I'm not very familiar with speaker diarization, so could you tell me what functionality from Praat you want to use? Most things that are possible in Praat should be accessible through Parselmouth (though not always through a nice shiny Python API, yet).

**Comment by YannickJadoul** [comment]
I'm closing this issue for now because of inactivity. Feel free to reopen if you need further clarification.
