### ISSUE TITLE
Could I only use C++ for  pitch extraction ?

### ISSUE THREAD

**Issue by ucasiggcas** [YannickJadoul/Parselmouth#16]
Dear,

Thanks to your great project, but if I want move it in cellphone , how should I do ?

Since I couldn't have the power to understand the praat source file in C++, so I can't know how to get the pitch.

Could You please help me ?

Maybe some API will be grateful.

Thanks a lot.

Lychee Tsu

**Comment by ucasiggcas** [comment]
Could the [script](https://github.com/YannickJadoul/Parselmouth/blob/master/src/parselmouth/Pitch.cpp) be used for pitch extraction ?

**Comment by YannickJadoul** [comment]
@ucasiggcas Thank you for your interest. The focus of Parselmouth is to provide a Python library for Praat, but Praat and its source code is freely available as open source project. http://praat.org. You could inspect the code there and use the C/C++ API. For example, [this](https://github.com/praat/praat/blob/5d008c82c0ec1992ee12500c53c64e8c66e9aede/fon/Sound_to_Pitch.cpp) is the source file containing the core of the pitch estimation algorithm.

I do not have an extensive knowledge of mobile development, but alternatively, I know there are projects such as kivy (https://kivy.org/#home, https://python-for-android.readthedocs.io/en/latest/) that allow you to program for Android with Python. However, you will need to compile Parselmouth and Praat for your target platform, given that Praat is written is C/C++.

**Comment by YannickJadoul** [comment]
So, this is not a issue for Parselmouth it seems. Further discussion is being done at [Gitter](https://gitter.im/PraatParselmouth/Lobby), so I'm closing this issue.
