### ISSUE TITLE
NameError: name 'parselmouth' is not defined,but I can use part of the module functions.

### ISSUE THREAD

**Issue by huiMM** [YannickJadoul/Parselmouth#19]
evn: 
Ubuntu  16.04+python 3.6 +pycharm

 **pip install praat-parselmouth**
 in my code:
 

> import parselmouth
>  print("version:",parselmouth.__version__)  
>  import parselmouth.WindowShape as windowshape
>  
> 
> > spectrogram = pre_emphasized_snd.to_spectrogram(window_length=0.03, maximum_frequency=8000                                              ,window_shape=windowshape.GAUSSIAN
> >                                                 )

**Error info:
    import parselmouth.WindowShape as windowshape
ModuleNotFoundError: No module named 'parselmouth.WindowShape'; 'parselmouth' is not a package**

If I remove the code "window_shape=windowshape.GAUSSIAN" and " import parselmouth.WindowShape as windowshape"
It's OK.

I am confused.
Thank you very much if you can give  me any help.

**Comment by YannickJadoul** [comment]
This is not a problem with Parselmouth, I believe. `parselmouth.WindowShape` is not a module but a class. You would the same error message for any other module.

The correct Python syntax is `from parselmouth import WindowShape` (or `from parselmouth import WindowShape as windowshape` if you mean to alias the class).

**Comment by huiMM** [comment]
Yes, Now it works.  Thanks a lot!
