### ISSUE TITLE
Could I get pitch correlation with Praat ?

### ISSUE THREAD

**Issue by Yablon** [YannickJadoul/Parselmouth#22]
Could I get pitch correlation with Praat  like reaper ? Thank you !

**Comment by YannickJadoul** [comment]
I don't know. What's "reaper"? Is it this: https://github.com/google/REAPER?
Can you do it with Praat itself? Parselmouth just provides a Python wrapper around Praat, but I don't know all the intricate details of what's available in there. So I'd ask the question at the Praat project, if I were you.

(By the way, we do have a [Gitter chatbox](https://gitter.im/PraatParselmouth/Lobby) for simple questions that aren't really bugs/problems.)
