### ISSUE TITLE
Importing parselmouth in psychopy

### ISSUE THREAD

**Issue by sallicap** [YannickJadoul/Parselmouth#24]
Hi!

I've successfully installed parselmouth (praat-parselmouth using pip) & wish to use it for a staircase SNR experiment I am creating in psychopy. When I go to import parlsemouth in a code component of my trial & then try to run it, psychopy says 

ModuleNotFoundError: No module named 'parselmouth'.

I am using Psyhopy3, python v 3.8 and on Mac OSX. I have tired uninstalling parselmouth & reinstalling but it doens't make a difference. Does anyone know how to fix this? Thank you!

**Comment by YannickJadoul** [comment]
Hi @sallicap!

How did you install PsychoPy? Did you install the standalone version on macOS? If so, the standalone version includes its own version of Python, and just using pip to install it your standard Python installation will not work, unfortunately.
There are separate instructions for installing Parselmouth into a standalone PsychoPy, though: https://parselmouth.readthedocs.io/en/stable/installation.html#psychopy.

Could you please try these instructions? If you already tried this, or anything is unclear in the instructions, or it still doesn't work afterwards, please do get back to me, and we'll further debug what's going wrong! :-)

**Comment by sallicap** [comment]
Dear Yannick - thank you for the quick reply and for your help!

I did indeed download the standalone version. Regarding the script for installing parlselmouth - does one just run this in the python shell on psychopy?

**Comment by YannickJadoul** [comment]
Great! Let's hope the script works, then :-)

> Regarding the script for installing parlselmouth - does one just run this in the python shell on psychopy?

Yes, you should run it from within the PsychoPy Coder interface/shell. It will basically follow the steps listed below, but it should do it automatically. If you want there are still two things you can customize in the script:

```
# CHANGE THESE VARIABLES TO CUSTOMIZE THE PARSELMOUTH INSTALLATION

# In which folder should Parselmouth be installed? Default: folder 'parselmouth-psychopy' in the home directory.
INSTALLATION_PATH = os.path.join(os.path.expanduser('~'), 'parselmouth-psychopy')

# Which version of Parselmouth should be installed ('x.y.z')? Default: the latest (None).
PARSELMOUTH_VERSION = None
```

**Comment by sallicap** [comment]
Thank you so much! The installation & parselmouth now works! :)

**Comment by YannickJadoul** [comment]
Great! Thanks for letting me know :-)
