### ISSUE TITLE
Saving Praat images

### ISSUE THREAD

**Issue by eginhard** [YannickJadoul/Parselmouth#28]
Is it possible to save Praat images to png files (or pdf for that matter) from Parselmouth?

Running the following script with `parselmouth.praat.run_file` creates the prapic file, but not the png one. `praat --run` creates both files.
```
Paint rectangle... 0.5 0 3 1 2
Save as praat picture file... test.prapic
Save as 300-dpi PNG file... test.png
```

Running on Linux with:
praat-parselmouth         0.3.3
python                    3.8.2

**Comment by YannickJadoul** [comment]
That's currently not possible, as far as I know. Praat depends on external libraries to provide this (e.g., `cairo` on Linux) and these get turned on by default when compiling without GUI and graphics. I haven't taken the time or done the effort to figure out how easy it is to enable this in Parselmouth (and to then be sure that it will work on every Python installation).

The situation is similar to the "barren server edition" of Praat (http://www.fon.hum.uva.nl/praat/download_linux.html), but it's a bit unfortunate that the scripts/actions still work, though; I agree.

I suppose you could save the Praat picture files, and "convert" these with a simple Praat script afterwards? (Or do some plotting yourself in a Python library.)

I'm also open to enable the graphics if it can be done reliably different platforms, though.

**Comment by eginhard** [comment]
Thanks for the quick feedback! That separate conversion will do for me.
