### ISSUE TITLE
sound.extract_left_channel() and call(sound, "Extract one channel", "Left")

### ISSUE THREAD

**Issue by nrgslp** [YannickJadoul/Parselmouth#29]
In Python 3.7.6, the following Parselmouth code

left = sound.extract_left_channel() 

and 

left = call(sound, "Extract one channel", "Left")

seems to produce the *right* channel (channel 2). 

sound.convert_to_mono() produces the same behavior.

**Comment by nrgslp** [comment]
It also says there is no channel 2 for the same file
    right = sound.extract_right_channel()

PraatError: There is no channel 2.
Sound "untitled": channel 2 not extracted.

![Annotation 2020-07-09 115441](https://user-images.githubusercontent.com/53921196/87062402-02f79500-c1db-11ea-9e3c-05ab743eaeca.png)

**Comment by nrgslp** [comment]
This issue was entered in error, sorry for the confusion.

**Comment by YannickJadoul** [comment]
No problem.
Just curious, for future reference: what went wrong? Was it a mono audio file to start with?
