### ISSUE TITLE
AttributeError: module 'parselmouth' has no attribute 'Sound'

### ISSUE THREAD

**Issue by iamsumitjangra** [YannickJadoul/Parselmouth#30]
Running into an error at the first line.

import parselmouth

import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

sns.set()

snd = parselmouth.Sound("the_north_wind_and_the_sun.wav")
plt.figure()
plt.plot(snd.xs(), snd.values.T)
plt.xlim([snd.xmin, snd.xmax])
plt.xlabel("time [s]")
plt.ylabel("amplitude")
plt.show() # or plt.savefig("sound.png"), or plt.savefig("sound.pdf")

------------------

File "parselmouth.py", line 1, in <module>
    import parselmouth
  File "/Users/shayana/Documents/work/dsp/parselmouth.py", line 10, in <module>
    snd = parselmouth.Sound("the_north_wind_and_the_sun.wav")
AttributeError: module 'parselmouth' has no attribute 'Sound'

**Comment by YannickJadoul** [comment]
@iamsumitjangra, could you try `print(parselmouth.__file__) ` before accessing `parselmouth.Sound`?
I suspect it will show that Python is confused by the name of your `parselmouth.py` file and the `parselmouth` library, so you'd have to rename that file.

**Comment by iamsumitjangra** [comment]
@YannickJadoul Thanks for pointing out this small mistake. Its working fine now.

**Comment by YannickJadoul** [comment]
Good to hear! Thanks for confirming :-)
