### ISSUE TITLE
Calculate Pitch and Formants frame wise

### ISSUE THREAD

**Issue by shakeel608** [YannickJadoul/Parselmouth#31]
How can we calculate pitch and formants on frame level. Suppose we we have and MFCC shape of (100, 39) and in order to append the pitch and formants to this shape, the pitch and formants need to be calculated at frame level  (i. I want to to define the wind-len and win-hop)

**Comment by YannickJadoul** [comment]
Praat has some descriptions on how the Pitch and Formant sampling is computed:
- https://www.fon.hum.uva.nl/praat/manual/Sound__To_Pitch__ac____.html
- https://www.fon.hum.uva.nl/praat/manual/Sound__To_Formant__burg____.html

But another, simpler way might just be to call `get_value_at_time` for all times in `mfcc.xs()`?

**Comment by YannickJadoul** [comment]
Given there's no answer, I'm going to consider this issue to be solved, and close it.
