### ISSUE TITLE
Typo in parselmouth.PraatError (opening 64-bit WAV)

### ISSUE THREAD

**Issue by Luke-Poeppel** [YannickJadoul/Parselmouth#35]
When trying to open a 64-bit WAV file in parselmouth (v0.3.3), we get the following error:
```
parselmouth.PraatError: Too few bits per sample (64; the maximum is 32).
```
If I'm not mistaken, the error should read: `Too many bits per sample (64; the maximum is 32).` The maximum allowed bit-depth is 32, so 64 is too high.

**Comment by YannickJadoul** [comment]
@Luke-Poeppel, thanks for reporting! This is Parselmouth forwarding a Praat error; luckily that one seems to have already been fixed: https://github.com/praat/praat/commit/c83430d5195d00ba03d20c5553ed06037fcc5f84 Seems Praat now also supports 64-bit WAV-files, even!

These changes have already been included on Parselmouth's development branch, but not yet released. Yes, it's urgent time Parselmouth gets a new release :-/ I'm planning to have one by the end of the year.

**Comment by Luke-Poeppel** [comment]
@YannickJadoul Great to hear –– looking forward to the next release :-) Thanks!
