### ISSUE TITLE
ImportError: cannot import name 'quote'

### ISSUE THREAD

**Issue by bmox** [YannickJadoul/Parselmouth#36]
ImportError: cannot import name 'quote'.

**Comment by YannickJadoul** [comment]
Please do some effort to explain your issue.

Also: #32
Also: https://parselmouth.readthedocs.io/en/stable/installation.html

> **Warning**
> 
> While the Python module itself is called `parselmouth`, the Parselmouth package on the Python Package Index has the name `praat-parselmouth`.
