### ISSUE TITLE
build problem on MacOSX Catalina

### ISSUE THREAD

**Issue by brianhtracey** [YannickJadoul/Parselmouth#37]
Hello, I had been happily using praat-parselmouth, but then upgraded my macOS to Catalina.  I had to upgrade Xcode and update my python setup, and am now having problems installing praat-parselmouth.  I think they are in the cmake step.  I'm seeing the following error messages, which all seem to come during compilation of Intensity.cpp: 

"Using incompatible compiler: compiler should provide either <optional> or <experimental/optional>". (3 places)
"use of undefined operator nullopt; did you mean nullptr?" (2 places)

My versions are below:
  gcc:  Apple clang version 12.0.0 (clang-1200.0.32.28)
  cmake version 3.19.2
  pip 20.3.3 from /usr/local/lib/python3.9/site-packages/pip (python 3.9)
  Python 3.9.1
  numpy 1.19.5

I'm guessing that I should install a different version of gcc or maybe cmake.  Do you have any suggestions?  I am not sure if I am giving the right info for debugging the problem.... just FYI I used homebrew to update my python and pip installations, if that would matter - though I'm guessing it's more of a Cpp compiler issue.  

Thank you for a great package!

**Comment by YannickJadoul** [comment]
Hi @brianhtracey. Apologies for these troubles, I've been postponing the release of pre-compiled Python 3.9 wheels while making some fixes for the next release.

I will look into this (thanks for all the version info; very useful), and I'll get back to you what's wrong. Your compiler version should be more than recent enough to have `<optional>`, so I don't understand what's wrong, there!

If you don't mind using the development version (it should be stable enough to use :-) ), you can download the correct pre-compiled wheel for Python 3.9 from here: https://github.com/YannickJadoul/Parselmouth/actions/runs/460053531 (download the "wheels" artifact from the bottom of the page, extract `praat_parselmouth-0.4.0.dev0-cp39-cp39-macosx_10_9_x86_64.whl`, and run `pip install` on that file`).

**Comment by brianhtracey** [comment]
that seems to work!  Much appreciated - and thank you for the extremely fast response.

**Comment by YannickJadoul** [comment]
Thanks for confirming, @brianhtracey.

So, for some reason, Apple seem to have removed the `<experimental/optional>` header, so it seems the `stable` branch can't be built with C++14 anymore. Luckily, this is fixed on the development branch (where Parselmouth now requries C++17), so this shouldn't happen anymore, soonish (after the 0.4.0 release).

**Comment by YannickJadoul** [comment]
0.4.0 was released. If this doesn't solve the issue out of the box, please let me know!
