### ISSUE TITLE
[dev issue] docs folder is not a parallel build ready

### ISSUE THREAD

**Issue by hokiedsp** [YannickJadoul/Parselmouth#40]
I'm trying to build the project on my Windows PC with Ninja+MSVC and CMake generate step fails with an error:

```
ninja: error: build.ninja:13872: multiple rules generate docs/doctrees [-w dupbuild=err]
```

This error apparently pops up when multiple cmake targets point to the same build folder/file.

The root cause of this issue seems to be in `docs\CMakeLists.txt` which reads

```cmake
add_custom_target(docs
        COMMAND ${CMAKE_COMMAND} -E env PYTHONPATH=$<TARGET_FILE_DIR:parselmouth> ${Python_EXECUTABLE} -m sphinx -M html ${CMAKE_CURRENT_SOURCE_DIR} ${CMAKE_CURRENT_BINARY_DIR}
        BYPRODUCTS doctrees/ html/
        DEPENDS parselmouth
        WORKING_DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR})

add_custom_target(docs_linkcheck
        COMMAND ${CMAKE_COMMAND} -E env PYTHONPATH=$<TARGET_FILE_DIR:parselmouth> ${Python_EXECUTABLE} -m sphinx -M linkcheck ${CMAKE_CURRENT_SOURCE_DIR} ${CMAKE_CURRENT_BINARY_DIR}
        BYPRODUCTS doctrees/ linkcheck/
        DEPENDS parselmouth
        WORKING_DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR})
```

There are 2 targets with the same BYPRODUCTS, thus a parallel builder sees an issue.

"I think" the fix is to combine it into one target:

```cmake
add_custom_target(docs
        COMMAND ${CMAKE_COMMAND} -E env PYTHONPATH=$<TARGET_FILE_DIR:parselmouth> ${Python_EXECUTABLE} -m sphinx -M html ${CMAKE_CURRENT_SOURCE_DIR} ${CMAKE_CURRENT_BINARY_DIR}
        COMMAND ${CMAKE_COMMAND} -E env PYTHONPATH=$<TARGET_FILE_DIR:parselmouth> ${Python_EXECUTABLE} -m sphinx -M linkcheck ${CMAKE_CURRENT_SOURCE_DIR} ${CMAKE_CURRENT_BINARY_DIR}
        BYPRODUCTS doctrees/ html/ linkcheck/
        DEPENDS parselmouth
        WORKING_DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR})
```

I said "I think" because I'm building the project outside of Python at the moment and cannot complete the docs build due to missing `parselmouth` package in Python. 

BTW, this is a great project, and I just dropped a note on Gitter for my intent to contribute FYI.

Best, 
Kesh

**Comment by YannickJadoul** [comment]
Hi @hokiedsp. Hmmm, I didn't get any issues with this, but then I wasn't using Ninja. I get the same warning with Ninja. However, I really intended to have two separate, independent targets, so your fix isn't exactly ideal either.

> BTW, this is a great project, and I just dropped a note on Gitter for my intent to contribute FYI.

I saw, yes, thanks! :-) Very excited to have contributions to Parselmouth! :-)

**Comment by YannickJadoul** [comment]
Fixed in https://github.com/YannickJadoul/Parselmouth/commit/5b96db6d65a545446885576f5bf75883303d6343, hopefully. If not, please reopen!

**Comment by hokiedsp** [comment]
May I ask why they need to be separate? I’m not well-versed in Sphinx to understand it (heck, this was the first time I encountered it myself. I’m fairly new to Python). It was just getting in my way to compile the rest. (Ninja goes so much faster than MSVC, it’s not even funny.) Sent from Mail for Windows 10 From: Yannick JadoulSent: Saturday, February 13, 2021 4:50 PMTo: YannickJadoul/ParselmouthCc: Kesh Ikuma; MentionSubject: Re: [YannickJadoul/Parselmouth] [dev issue] docs folder is not a parallel build ready (#40) Hi @hokiedsp. Hmmm, I didn't get any issues with this, but then I wasn't using Ninja. I get the same warning with Ninja. However, I really intended to have two separate, independent targets, so your fix isn't exactly ideal either.BTW, this is a great project, and I just dropped a note on Gitter for my intent to contribute FYI.I saw, yes, thanks! :-) Very excited to have contributions to Parselmouth! :-)—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by YannickJadoul** [comment]
> May I ask why they need to be separate?

Sure. The idea was to have just separate targets and have `linkcheck` optional (it shouldn't be run every time when building locally; it's run on CI anyway).

> (Ninja goes so much faster than MSVC, it’s not even funny.)

Ha, I've heard that one before ;-) I'm on Linux, so the speedup over `make` is reasonably minor.

Thanks for tracking the issue down so well, btw! It was a quick fix, this way!
