### ISSUE TITLE
Segfault when computing formants on stereo audio from array

### ISSUE THREAD

**Issue by hadware** [YannickJadoul/Parselmouth#45]
Hey, 

First, i'd like to thank you again for your work on parselmouth. It's an amazing work.
I ran into a small problem that can become a bit troublesome since this won't output any stacktrace. 
An example is worth a thousand words:

```python3
from parselmouth import Sound
from scipy.io.wavfile import read
rate, array = read("some_stereo_audio.wav")
snd = Sound(array, rate)
snd.to_formant_burg() # <--------- this will segfault
```

However, this works if I load the sound directly from the path (`snd = Sound("some_stereo_audio.wav")`).

I'm running python 3.8 on ubuntu, but this segfaulted all the same on a python 3.7 on centos. I tested it on all parselmouth versions >= 0.3.2

**Comment by YannickJadoul** [comment]
Hi, @hadware. Thanks for the kind words!

I tried to reproduce, but I can't really do so with my example file, it seems:

```pycon
>>> import parselmouth
>>> parselmouth.Sound("the_north_wind_and_the_sun.wav").to_formant_burg()
<parselmouth.Formant object at 0x7f2b8a44cbc8>
>>> from scipy.io.wavfile import read
>>> rate, array = read("the_north_wind_and_the_sun.wav")
>>> parselmouth.Sound(array, rate).to_formant_burg()
<parselmouth.Formant object at 0x7f2b8604dc00>
```

However, one thing to note is that Praat works with floating point numbers (between -1.0 and 1.0) and thus, `parselmouth.Sound` expects those as well. Meanwhile, I see that `array` is a bunch of raw `int16`s (or another type, probably depending on the exact WAVE format) coming from SciPy.

That's not reason to segfault, though, so I'm curious to figure out what goes wrong. But scaling by dividing by `2**15` (for `int16`; some other number for other size integers, ofc) might be a solution.

Do you have an audio file that demonstrates your issue and that you're free/able to share such that I could reproduce? (by mail or in a private Gitter message, if you don't want to put it public, is fine as well)

**Comment by hadware** [comment]
Here's a file that i used to reproduce the bug. You can thank @mmmaat for his vocal performance. 

[pho_a.zip](https://github.com/YannickJadoul/Parselmouth/files/6004676/pho_a.zip)

**Comment by YannickJadoul** [comment]
> Although it's true that this array is int16-formatted (now that you mention it, I might have to change some things in my feature-extraction code sweat_smile ).

Well, in principle, Praat will just think it's VERY LOUD, I suppose. Worth the comparison, anyway. (And clearly some documentation to be done on my part.)

> The weird thing is that mono-channel int16-formatted arrays seem to work fine (or a least, not to make parselmouth crash). How is that?

Oh, good point! I skimmed over the "stereo" part, it seems, when I tried out things!

> [pho_a.zip](https://github.com/YannickJadoul/Parselmouth/files/6004676/pho_a.zip)

Thanks. And beautiful indeed, @mmmaat ;-)

**Comment by YannickJadoul** [comment]
Depends a bit on your definition of "good news", but good news! I managed to reproduce:

```pycon
>>> parselmouth.Sound(*reversed(scipy.io.wavfile.read("a_mathieu_stereo.wav"))).to_formant_burg()
munmap_chunk(): invalid pointer
Aborted (core dumped)
```

(arguably, this code also deserves to segfault, but fine)

**Comment by YannickJadoul** [comment]
Aha, I see. Seems Praat doesn't like it too much that you pass 221053 channels with 2 samples each:

```pycon
>>> parselmouth.Sound(*reversed(scipy.io.wavfile.read("a_mathieu_stereo.wav"))).values.shape
(221053, 2)
>>> parselmouth.Sound("a_mathieu_stereo.wav").values.shape
(2, 221053)
```

This is a) rather unfortunate, and b) still kind of crappy that Praat crashes on it. But at least it's an explanation of what's different. I'll still see if I can track down the bug in Praat and report upstream, though :-)

**Comment by hadware** [comment]
Well, on my side, the good news is that Praat doesn't seem to care much about the encoding format anyway: int16 or float64 (normalized by `2 ** 15`) produced the same results.

> Aha, I see. Seems Praat doesn't like it too much that you pass 221053 channels with 2 samples each:
> 
> ```
> >>> parselmouth.Sound(*reversed(scipy.io.wavfile.read("a_mathieu_stereo.wav"))).values.shape
> (221053, 2)
> >>> parselmouth.Sound("a_mathieu_stereo.wav").values.shape
> (2, 221053)
> ```

Aaaaah i'll be damned, i'd never have thought of checking the array shape. Is there any "standard" way of representing audio arrays?

**Comment by YannickJadoul** [comment]
> Well, on my side, the good news is that Praat doesn't seem to care much about the encoding format anyway: int16 or float64 (normalized by `2 ** 15`) produced the same results.

Ooof, that does make sense. Luckily  :-)

> Is there any "standard" way of representing audio arrays?

I don't know. To some degree, `(n_samples, n_channels)` does make more sense to me, actually, but I decided to follow Praat, as it considers the samples the x-axis and the channels the y-axis (and maps a `Matrix` as shape (y-axis, x-axis)) ... :-/

**Comment by YannickJadoul** [comment]
> I don't know. To some degree, `(n_samples, n_channels)` does make more sense to me, actually, but I decided to follow Praat, as it considers the samples the x-axis and the channels the y-axis (and maps a `Matrix` as shape (y-axis, x-axis)) ... :-/

See here, btw: https://www.fon.hum.uva.nl/praat/manual/Matrix.html

I had first matched SciPy's format, but thought consistency within Praat and Parselmouth was probably more important :-/ Now I'm doubting that decision a bit.

**Comment by hadware** [comment]
In any case, even if we have data formatted in scipy's convention, it's just a `swappaxes` away from Praat's (and thus parselmouth's) convention. Maybe just show a warning if the channel dimension appears to be larger than the sample dimension?

**Comment by YannickJadoul** [comment]
> In any case, even if we have data formatted in scipy's convention, it's just a `swapaxes` away from Praat's (and thus parselmouth's) convention.

Even better. Just a `array.T` to transpose ;-)

> Maybe just show a warning if the channel dimension appears to be larger than the sample dimension?

That's an interesting suggestion, though, yes! It would be very weird data where that's not the case! Thanks for the suggestion.

**Comment by YannickJadoul** [comment]
@hadware, finally found, and reported upstream: praat/praat#1599

Also, I've added a warning, for the future, in 69335fcab8c38600375743937ec25878be1ad165. Thanks for the suggestion! :-)

**Comment by hadware** [comment]
Neat! this is what we can call a prompt reaction.

**Comment by YannickJadoul** [comment]
Let's hope 0.5.0 doesn't take as long as 0.4.0 did, though ;-)
