### ISSUE TITLE
ImportError: cannot import name 'quote' from 'urllib' (/usr/lib/python3.7/urllib/__init__.py)

### ISSUE THREAD

**Issue by amine-boukriba** [YannickJadoul/Parselmouth#49]
i am using praat from parselmouth in gooogle colab and i am getting this error when importing from **parselmouth.praat import call**
```
/usr/local/lib/python3.7/dist-packages/parselmouth/adapters/dfp/interface.py in <module>()
     15 from datetime import timedelta
     16 from pytz import timezone
---> 17 from urllib import quote
     18 
     19 # Parselmouth Imports

ImportError: cannot import name 'quote' from 'urllib' (/usr/lib/python3.7/urllib/__init__.py)
```

i tried installing diffirent version of urllib but nothing worked
i know that urllib uses  import urllib.parse.quote instead offrom urllib import quote  but i am not the one importing the urllib package it s the praat module and i cannot change it

**Comment by YannickJadoul** [comment]
@amine-boukriba, you must have `pip install`ed the `parselmouth` package. Not `praat-parselmouth`. See https://parselmouth.readthedocs.io/en/stable/installation.html.

**Comment by YannickJadoul** [comment]
I'm going to consider this solved. If not, please reopen.
