### ISSUE TITLE
"parselmouth.praat.run_file" is not thread safe?

### ISSUE THREAD

**Issue by ananas-hebo** [YannickJadoul/Parselmouth#54]
```
objects = run_file(mltrnl_praat, -20, 2, 0.3, "no", wavfile, path, 80, 400, 0.01, capture_output=True)
print(objects)
```

The arguments is same, but sometimes return objects is not same.

run_file can be called by different threads?

**Comment by YannickJadoul** [comment]
@ananas-hebo Can you give some more information?
- In which context are you running this? Are you running in threads?
- What are "not the same return objects"?
- What is the script you're running?

In general, Praat is not thread safe, but normally Parselmouth does not release the Python GIL anywhere, so things shouldn't run multithreaded anyway.

**Comment by ananas-hebo** [comment]
@YannickJadoul 

Thanks for your reply! Parselmouth should be thread safe, that maybe other wrong.

As praat reference point 4 say:

_Praat will execute the script my script.praat without showing Praat's GUI, i.e. without showing its usual two windows. In fact, any output that would normally go to the Info window, will now go directly to the Console window in which you typed the command. If Praat was already running when you typed the command, its windows will not be affected. In fact, the GUI-instantiation of Praat and the Console-instantiation can run simultaneously without them noticing each other's existence; moreover, multiple Console-instantiations of Praat can run simultaneously, each in their own Console._

https://www.fon.hum.uva.nl/praat/manual/Scripting_6_9__Calling_from_the_command_line.html



I upload the code can reproduct this error.

praat script from https://github.com/Shahabks/myprosody .
When I added reduce noise code, 'print(objects)' is going to change randomly.
```
################
# Reduce noise method

reduce_noise_method$ = "spectral-subtraction"
soundid = Reduce noise... 0.0 0.0 0.025 80.0 10000.0 40.0 -20.0 spectral-subtraction

select 'soundid'
soundname$=selected$("Sound")
################
```

output:

```
([<parselmouth.Pitch object at 0x7f8872b31b30>], '1.0083749999999982\t8.070333333333332\t21.04\t2.3925591410712674\t4.1630529054640055\t119.6378391697134\t359.39599999999996\t1.25881624973951\t1.318182169408654\t143.03332689345623\t1.1702111810684468\t24.237615006015407\t216.27729785913144\t107.14888702526028\t15\t0.7272727272727273\t2.684998030950949\t0.5884331155606723\t48\t4\t5\t21\t21\tc\t2.7600000000000002\tB2\t3.4694973359216887\n')
([<parselmouth.Pitch object at 0x7f8872b31b30>], '1.0083749999999982\t8.070333333333332\t21.04\t2.3925591410712674\t4.1630529054640055\t119.6378391697134\t359.39599999999996\t1.2588162497757414\t1.3181821694028244\t143.03332689351083\t1.1702111810678384\t24.237615005166457\t216.2772978593421\t107.1488870222008\t15\t0.7272727272727273\t2.684998027954994\t0.5884331173653298\t48\t4\t5\t21\t21\tc\t2.7600000000000002\tB2\t3.4694973359216887\n')
([<parselmouth.Pitch object at 0x7f8872b31b30>], '1.0083749999999982\t8.070333333333332\t21.04\t2.3925591410712674\t4.1630529054640055\t119.6378391697134\t359.39599999999996\t1.2588162497757414\t1.3181821694028244\t143.03332689351083\t1.1702111810678384\t24.237615005166457\t216.2772978593421\t107.1488870222008\t15\t0.7272727272727273\t2.684998027954994\t0.5884331173653298\t48\t4\t5\t21\t21\tc\t2.7600000000000002\tB2\t3.4694973359216887\n')
([<parselmouth.TextGrid object at 0x7f8872b31b30>], '0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\n')
([<parselmouth.Pitch object at 0x7f8872b31b30>], '1.0083749999999982\t8.070333333333332\t21.04\t2.3925591410712674\t4.1630529054640055\t119.6378391697134\t359.39599999999996\t1.2585628755381582\t1.3177387303107029\t142.81765525333662\t1.1701164315601391\t24.232673505455036\t216.27724846705854\t107.1492162368577\t15\t0.7272727272727273\t2.6849983628779124\t0.5884334417046939\t48\t4\t5\t21\t21\tc\t2.7600000000000002\tB2\t3.4694973359216887\n')
([<parselmouth.Pitch object at 0x7f8872b31b30>], '1.0083749999999982\t8.070333333333332\t21.04\t2.3925591410712674\t4.1630529054640055\t119.6378391697134\t359.39599999999996\t1.258816249741289\t1.318182169411553\t143.03332689351475\t1.170211181066566\t24.23761500590128\t216.2772978592322\t107.14888701873221\t15\t0.7272727272727273\t2.6849980274119543\t0.5884331176335096\t48\t4\t5\t21\t21\tc\t2.7600000000000002\tB2\t3.4694973359216887\n')
([<parselmouth.Pitch object at 0x7f8872b31b30>], '1.0083749999999982\t8.070333333333332\t21.04\t2.3925591410712674\t4.1630529054640055\t119.6378391697134\t359.39599999999996\t1.2588162497757414\t1.3181821694028244\t143.03332689351083\t1.1702111810678384\t24.237615005166457\t216.2772978593421\t107.1488870222008\t15\t0.7272727272727273\t2.684998027954994\t0.5884331173653298\t48\t4\t5\t21\t21\tc\t2.7600000000000002\tB2\t3.4694973359216887\n')
```
[parselmouth.zip](https://github.com/YannickJadoul/Parselmouth/files/6573161/parselmouth.zip)

**Comment by YannickJadoul** [comment]
> As praat reference point 4 say:

Right. But those are separate processes then ("moreover, multiple Console-instantiations of Praat can run simultaneously, each in their own Console."), and not multiple threads in the same process.

Anyway, Parselmouth is not releasing the GIL, so normally it can not even be run multithreaded.

**Comment by YannickJadoul** [comment]
> [parselmouth.zip](https://github.com/YannickJadoul/Parselmouth/files/6573161/parselmouth.zip)

Thank you for this! I tried running the example, but didn't manage to actually reproduce the problem. All my output is rather consistently the same. Any idea if there's a way I can reproduce this? Are you running on Windows?

At any rate, this is not doing things multi-threaded, so if anything's wrong, it's a real bug:

```py
for i in range(100):
    run_praat_file()
```

**Comment by ananas-hebo** [comment]
I test on macos  11.2.3 (20D91)

![E384C5C5-B1FB-42B0-87DD-D55772A1A8C4](https://user-images.githubusercontent.com/5362672/120418147-948f6880-c392-11eb-90e2-0816da3167f4.png)

**Comment by YannickJadoul** [comment]
Thank you for this further information, @ananas-hebo. I managed to reproduce this on a Windows installation, so I can further debug!

**Comment by YannickJadoul** [comment]
I finally found the bug in Praat, in `"Reduce noise..."`, and reported it upstream: praat/praat#1873

So, this does not seem to be a Parselmouth issue, luckily! :-) The solution is to not use `"Reduce noise..."` in your scripts (or at least not depend on it being always right, I guess), until Praat has fixed this upstream and Parselmouth gets update.

Thanks for reporting, @ananas-hebo!

**Comment by YannickJadoul** [comment]
> run_file can be called by different threads?

For the record, `run_file` won't run parallel in different threads (because of the Python GIL, which Parselmouth does not (yet?) release), but it should be possible to use it from different threads.
