### ISSUE TITLE
How to change advanced pitch settings?

### ISSUE THREAD

**Issue by amadeusuzx** [YannickJadoul/Parselmouth#55]
Hi there,
there is advanced pitch settings that allows to change parameters like voicing threshold in Praat, how can I modify those settings in Parselmouth?

**Comment by YannickJadoul** [comment]
You can pass all of these as parameters, just like in Praat: https://parselmouth.readthedocs.io/en/stable/api_reference.html#parselmouth.Sound.to_pitch_ac

Alternatively, you can call `path_finder` on an existing Pitch object: https://parselmouth.readthedocs.io/en/stable/api_reference.html#parselmouth.Pitch.path_finder, which corresponds to clicking that menu action in the Praat Pitch editor.

**Comment by amadeusuzx** [comment]
Many Thanks!
