### ISSUE TITLE
Library Installation

### ISSUE THREAD

**Issue by BanekMan** [YannickJadoul/Parselmouth#56]
Hi,
I want to ask why, after the installation process, PyCharm does not have the library referenced in the example code. The installation only creates a dist-info folder, and importing the parselmouth library in the code generates an error ModuleNotFoundError: No module named 'parselmouth'.
![image](https://user-images.githubusercontent.com/31101049/128304133-aa554360-628e-42d0-8e84-8e209e2f8a2b.png)

Python Version - 3.8.10
Ubuntu 20.04.2 LTS

**Comment by YannickJadoul** [comment]
Hi, @BanekMan, how did you install? This `dist-info` folder is not really normal to have in your project (or I don't know what folder you're showing there).

Next, is it showing an error when running, or just underlining? With the kind of extension-modules, things can be more complicated, sometimes, so you need to make sure you run it and not trust the red underlines.

If neither of these solve it, I'll need a bit more info, but then we'll look further :-)

**Comment by BanekMan** [comment]
Hi, 
Installation was like in documentation with `pip install praat-parselmouth`
![image](https://user-images.githubusercontent.com/31101049/128468583-d1c3d28b-70fa-4a2a-a74f-1d4da31d873f.png)
Folder dist-info is in ExternalLibraries/Python 3.8/site-packages
I`m just not trust red underlines and it solved problem. This is not usually solution but in that case I can use that.
Thks and best regards

**Comment by YannickJadoul** [comment]
@BanekMan, you're not the only one with this kind of issue, it seems. In general, PyCharm seems to sometimes fail to do this for binary/compiled Python modules. Maybe some of these answers can help you, to force PyCharm to generate the "skeletons" for Parselmouth?

https://stackoverflow.com/questions/5049842/autocomplete-in-pycharm-for-python-compiled-extensions
https://stackoverflow.com/questions/26023784/code-completion-in-pycharm-with-introspective-bindings
