### ISSUE TITLE
pip: praat-parselmouth-0.3.2.post2.tar.gz has inconsistent version: filename has '0.3.2.post2', but metadata has '0.3.2'

### ISSUE THREAD

**Issue by antonakv** [YannickJadoul/Parselmouth#65]
requirements.txt:

```
praat-parselmouth>=0.3.2
```

Run

```
pip3 install -r requirements.txt
```

 WARNING: Requested praat-parselmouth>=0.3.2.post2 from https://files.pythonhosted.org/packages/0e/7e/f18db0e8b7057966766a452bfd57be13a5871ef920616451e9ba6eead664/praat-parselmouth-0.3.2.post2.tar.gz#sha256=64b085e95ee06b06b124e493e2e3ef57179e89ec8b34dac59bce12ccb6d6c335 (from -r requirements.txt (line 7)), but installing version 0.3.2
WARNING: Discarding https://files.pythonhosted.org/packages/0e/7e/f18db0e8b7057966766a452bfd57be13a5871ef920616451e9ba6eead664/praat-parselmouth-0.3.2.post2.tar.gz#sha256=64b085e95ee06b06b124e493e2e3ef57179e89ec8b34dac59bce12ccb6d6c335 (from https://pypi.org/simple/praat-parselmouth/). Requested praat-parselmouth>=0.3.2.post2 from https://files.pythonhosted.org/packages/0e/7e/f18db0e8b7057966766a452bfd57be13a5871ef920616451e9ba6eead664/praat-parselmouth-0.3.2.post2.tar.gz#sha256=64b085e95ee06b06b124e493e2e3ef57179e89ec8b34dac59bce12ccb6d6c335 (from -r requirements.txt (line 7)) has inconsistent version: filename has '0.3.2.post2', but metadata has '0.3.2'

**Comment by YannickJadoul** [comment]
Thanks for reporting, @antonakv.
