### ISSUE TITLE
How to match time steps?

### ISSUE THREAD

**Issue by intory89** [YannickJadoul/Parselmouth#67]
I want to match time steps between mel-spectrogram and pitch or mel-spectrogram and intensity.

for example. I convert Audio A to mel-spectrogram that size of [682, 3663], and to pitch that size of  [28]

Thanks.

**Comment by YannickJadoul** [comment]
Hi, @intory89. One way to do this is to look at Praat's documentation and see how time steps are determined from the parameters you pass to the various analysis methods. Praat tends to describe well how these step sizes are calculated.
 
However, I would suggest to use the interpolation functionality that's part of many of these analyses. For example, by using [`parselmouth.Pitch.get_value_at_time`](https://parselmouth.readthedocs.io/en/stable/api_reference.html#parselmouth.Pitch.get_value_at_time), you can get Praat/Parselmouth to get the interpolated pitch value at that specific point in time.
This second method will be less cumbersome (but will also be less efficient, of course) than matching the analyses' time steps.

**Comment by YannickJadoul** [comment]
By the way, for these kind of questions that aren't really issues in Parselmouth, there is the [Gitter chat box](https://gitter.im/PraatParselmouth/Lobby) where people will answer your questions probably much more quickly.

**Comment by 980202006** [comment]
Is there a usage example of parselmouth.Pitch.get_value_at_time？

**Comment by YannickJadoul** [comment]
@980202006, errrrm, I'm not sure about a usage example (I don't think there's one in the docs), but this should help? https://parselmouth.readthedocs.io/en/stable/api_reference.html#parselmouth.Pitch.get_value_at_time
So in its basic for, it's really just `pitch_object.get_value_at_time(t)`.

Apart from that, you can always refer to the Praat docs, to get more background?

**Comment by julian24bas** [comment]
Hi @YannickJadoul ``pitch_object.get_value_at_time(t)`` works fine for me to get the interpolated values for the frequency. However I also need the interpolated value for the pitch strength at the same timestamp but this method only gives me the frequency. For now I extracted the strength and corresponding timestamps following your [example](https://github.com/YannickJadoul/Parselmouth#readme) on how to create pitch plots and used scipy interpolation to do the job.
````
pitch = sound.to_pitch()
pitch_strength_y = pitch.selected_array["strength"]
pitch_x = pitch.xs()
pitch_strength_f = interp1d(x=pitch_x, y=pitch_strength_y, kind="linear", bounds_error=False)
pitch_strength_t = pitch_strength_f(t)
````
I have the same problem for getting MFCC values for specific timestamps. And "solved" it using the same scipy approach and your explanation for MFCCs [here](https://github.com/YannickJadoul/Parselmouth/issues/21).
````
mfcc = sound.to_mfcc(number_of_coefficients=2)
mfcc_coeff = mfcc.to_array()
mfcc_0_y = mfcc_coeff[1]
mfcc_1_y = mfcc_coeff[2]
mfcc_x = mfcc.xs()
mfcc_0_f = interp1d(x=mfcc_x, y=mfcc_0_y, kind="linear", bounds_error=False)
mfcc_1_f = interp1d(x=mfcc_x, y=mfcc_1_y, kind="linear", bounds_error=False)
mfcc_0_f(audio_x)
mfcc_1_f(audio_x)
````
This is ok but when testing and comparing it with the pitch frequency for some timestamps the results where not identical to the praat method ``pitch_object.get_value_at_time(t)``. In Addition this seems to be a more complicated solution than it should be. So I feel like I'm missing something. For the MFCC I do not know if this is a proper approach as I did not find anything on the Praat official website or the Parselmouth Docs on how to interpolate MFCCs, whereas for harmonicity or intensity it's mentioned that a cubic interpolation should be used and for pitch a linear interpolation.

Do you know how to get the pitch strength and MFCCs at a specific timestamp?
