### ISSUE TITLE
Suds-jurko error while installing

### ISSUE THREAD

**Issue by 16DF35DC5E7F679EF7C096F61B79B679** [YannickJadoul/Parselmouth#69]
`poetry add Parselmouth`

Package operations: 10 installs, 0 updates, 0 removals

  • Installing pyparsing (3.0.6)
  • Installing httplib2 (0.20.2)
  • Installing oauth2client (4.1.3)
  • Installing pysocks (1.7.1)
  • Installing pytz (2015.7)
  • Installing pyyaml (6.0)
  • Installing suds-jurko (0.6): Failed

  EnvCommandError

  ERROR: Command errored out with exit status 1:
  
 error in suds-jurko setup command: use_2to3 is invalid.

Failed to add packages, reverting the pyproject.toml file to its original content.

Python: v.3.9.8
Os: MacOs Catalina

**Comment by YannickJadoul** [comment]
The package on PyPI for Parselmouth is (unfortunately) praat-parselmouth: https://pypi.org/project/praat-parselmouth/
See/read also here: https://parselmouth.readthedocs.io/en/stable/installation.html
