### ISSUE TITLE
pipenv install error

### ISSUE THREAD

**Issue by MitchellAcoustics15** [YannickJadoul/Parselmouth#7]
Hello,

I'm trying to install parselmouth through pipenv on Windows and get this error:

```
Error:  An error occurred while installing praat-parselmouth!
  Failed building wheel for praat-parselmouth
Command "c:\users\mitch\.virtualenvs\pipenv-trial2-88_u4rjn\scripts\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\mitch\\AppData\\Local\\Temp\\pip-install-_mw2pug9\\praat-parselmouth\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\mitch\AppData\Local\Temp\pip-record-ox_jq1ly\install-record.txt --single-version-externally-managed --compile --install-headers c:\users\mitch\.virtualenvs\pipenv-trial2-88_u4rjn\include\site\python3.7\praat-parselmouth" failed with error code 1 in C:\Users\mitch\AppData\Local\Temp\pip-install-_mw2pug9\praat-parselmouth\
```

I have also previously tried to install directly with pip and received a similar error. I should also note this issue is only occurring on Windows, I was able to install and use it easily on Linux. 

Thanks

**Comment by YannickJadoul** [comment]
Hi @MitchellAcoustics15. As far as I can see from the error message, you are trying to install Parselmouth in Python 3.7? If so, that explains the problem, because I have not yet made a release that supports Python 3.7.

However, Parselmouth works on Python 3.7, so give me a little bit of time, and I'll make a new release today that includes Python 3.7!

**Comment by YannickJadoul** [comment]
@MitchellAcoustics15 Done! I've just release [Parselmouth 0.3.1](https://github.com/YannickJadoul/Parselmouth/releases/tag/v0.3.1). Normally, you should now be able to install Parselmouth? Could you let me know if that is indeed the case?

**Comment by MitchellAcoustics15** [comment]
It works perfectly! Thanks so much!

**Comment by YannickJadoul** [comment]
Great to hear! :-)
Thanks for reporting and having me finally make that release!
