### ISSUE TITLE
Segmentation fault (core dumped) on ppc64le

### ISSUE THREAD

**Issue by auspicious3000** [YannickJadoul/Parselmouth#71]
System: power 9, linux ppc64le
Anaconda version: Anaconda3-2021.11-Linux-ppc64le.sh, Anaconda3-2020.11-Linux-ppc64le.sh
python version: 3.7, 3.8
parselmouth version: 0.4.0

After successful installation using pip install,  'import parselmouth' gives Segmentation fault (core dumped). 
parselmouth version 0.3.3 can work but I would like to install 0.4.0. 

Are there alternative ways to install such as compiling from source?

Thanks!

**Comment by YannickJadoul** [comment]
@auspicious3000, sorry for the delay. My laptop gave up on me, unfortunately...

So, about your issue: I didn't even know Parselmouth works on ppc64le? I only provide pre-compiled wheels for Intel (and Apple's new chip), I think, so you must have compiled it yourself already?

Apart from that, I don't really know why 0.3.3 would work but 0.4.0 not. Do you have any more information about the segfault?
You could try to build a debug build (clone/download the repository, CMake build into a build directory, add the `src` subdir in the build directory in the `PYTHONPATH` environment variable, and run Python), and run python and the import through gdb, and get a stack trace. But no guarantees that it will actually provide much useful information, ofc.

I don't have access to a PowerPC system, though. I'd be curious to try some things out if there's a way to get access (but still no guarantees on actually finding/fixing the bug!).

**Comment by auspicious3000** [comment]
Yes, it worked on one powerpc system when I was raising the "change gender" problem. This segmentation fault happens when I moved to a different powerpc system. The brainless "fix" is to import sklearn before importing parselmouth.

**Comment by YannickJadoul** [comment]
Huh, OK. Well, thanks, good to know!

> The brainless "fix" is to import sklearn before importing parselmouth.

That's ... quite scary, that such a thing works, actually.
Well, if it works for you, and you need to carry on, why not. But if you would be interested in getting a true fix and can produce a stack trace of the crash, I'd be interested in having a look as well.
