### ISSUE TITLE
External documentation for praat.call()?

### ISSUE THREAD

**Issue by atyshka** [YannickJadoul/Parselmouth#75]
Thanks for making this awesome project! I'm working on a voice changer program using this, and trying to use some more advanced features. Do you have any good references on how to use the praat.call() syntax? I'm not asking for clarification in your docs, more like a link to an external source that describes this Praat scripting language. [This site](https://www.fon.hum.uva.nl/praat/manual/Sound__Change_gender___.html) is the closest thing I've found but it doesn't seem to show the direct syntax to use, it seems more oriented toward the GUI.

**Comment by atyshka** [comment]
Like where did you discover all the commands to use for the pitch manipulation tutorial in your docs? https://parselmouth.readthedocs.io/en/stable/examples/pitch_manipulation.html

**Comment by YannickJadoul** [comment]
Thanks, @atyshka, that's great to hear :-)

> [This site](https://www.fon.hum.uva.nl/praat/manual/Sound__Change_gender___.html) is the closest thing I've found but it doesn't seem to show the direct syntax to use, it seems more oriented toward the GUI.

I'm afraid that's the best I have on offer, though. `call` is giving you direct Python access to Praat's actions, which would be called from the GUI or in a Praat script. You are right that these are rather GUI-based (as Praat itself is), but I'm afraid that there's not a huge lot I can do about it. Parselmouth is merely providing access to what's available in Praat, so any documentation or list of functionality I add on this would possibly be outdated rather quickly, and I would also mainly base myself on Praat's documentation.

That being said, I do have a few suggestions that might help you:

- https://www.fon.hum.uva.nl/praat/manual/ shows the index of all Praat documentation pages. Unfortunately, I know that not every command in Praat has a help page, so this won't be a complete list.
- > Like where did you discover all the commands to use for the pitch manipulation tutorial in your docs? https://parselmouth.readthedocs.io/en/stable/examples/pitch_manipulation.html

  I typically open the Praat user interface and manually click around to see what functionality and analyses are available. It is (o me) also just easier to explore and get the interactive views of the GUI. Once you figure out the analyses you want to do, it is reasonably straightforward to translate the steps you followed into calls of Parselmouth functions, and automate these for your whole dataset. Or you want to analyse some results with a Python library, you can always save the Praat object to a file (text or binary), and use `parselmouth.read` to open it in Python.
- If you really feel very adventurous, there are the two hidden, non-public functions `parselmouth.praat._get_actions()` and `parselmouth.praat._get_menu_commands()`. These things will read some internal list in Praat which contains all actions known to Praat. But these don't have any explanation, I'm afraid; for that you will have to search Praat's docs or Google. But please be aware that these two Parselmouth functions are meant to change without warning, so by all means, use them to check what's available, but don't depend on the API (or don't come complaining if this API changes in a future version) ;-)

I hope this helps? I'll close this, but if you have any further questions, do not hesitate to reopen and ask (or pass by [Gitter](https://gitter.im/PraatParselmouth/Lobby)) !
