### ISSUE TITLE
Is it possible to extract pitch using Parselmouth with only mel-spectrograms provided?

### ISSUE THREAD

**Issue by Charlottecuc** [YannickJadoul/Parselmouth#76]
Is it possible to extract pitch using Parselmouth with only mel-spectrograms provided (not with waveform)?
Thank you.

**Comment by YannickJadoul** [comment]
Hi, @Charlottecuc. I don't know all the available functionality in Praat, but I've never encountered something like that. And at a first glance I can't really find it in Praat's GUI functionality, which means it also won't be available in Parselmouth.

Apart from seeing if there are different pitch detection algorithms in the literature that would work on spectrograms (I honestly have no idea, but there could be; worth a search), there's one thing I could come up with: if you can convert the mel scale spectrogram to a Hz scale, and then use the [librosa](https://librosa.org/doc/latest/index.html) library to reconstruct the audio (see https://librosa.org/doc/latest/generated/librosa.griffinlim.html), you could use Parselmouth to run Praat's pitch tracking algorithm on that?
Actually, looking at it more closely, it seems that librosa might have a reconstruction algorithm for mel-spectrograms, even? https://librosa.org/doc/latest/generated/librosa.feature.inverse.mel_to_audio.html#librosa.feature.inverse.mel_to_audio Matching Praat's parameters to librosa might take a while, but should be possible.

But I must say, if I look at a Praat MelSpectrogram, the spectrogram seems to be rather course by default, so I wonder if there is enough information to extract a precise enough pitch.

**Comment by YannickJadoul** [comment]
At any rate, if anything is possible, with Praat, I'd be happy to help you turn it into a Python script with Parselmouth :-) I'll also tag @hokiedsp, who might have some more ideas, in addition to mine above.

**Comment by hokiedsp** [comment]
@Charlottecuc - I don't have much to add. @YannickJadoul covered my ideas and more. One other idea would be to convert it to MFCC and derive the pitch from the dominant non-zero peak. Not sure, never dealt with MFCC before but it seems plausible.

**Comment by YannickJadoul** [comment]
Thanks, @hokiedsp!

At any rate, seems there's nothing specific for this in Praat, so it's also nothing Parselmouth would support out of the box (at least, definitely not at this stage). So I'll close this, but if you do run into Parselmouth issues, feel free to reopen, open another issue, or just pass by [Gitter](https://gitter.im/PraatParselmouth/Development).

**Comment by Charlottecuc** [comment]
Thank you 👍
