### ISSUE TITLE
Formant calculation not as accurate as in the Praat software

### ISSUE THREAD

**Issue by hykilpikonna** [YannickJadoul/Parselmouth#78]
I tried to use Parselmouth's `to_formant_burg(time_step=0.032)` to calculate formants, but the returned values on the same audio file are very inaccurate compared to results from the Praat software. What are some potential causes for this difference in accuracy with the same software? Is it possible that Praat is using [To Formant (robust)](https://www.fon.hum.uva.nl/praat/manual/Sound__To_Formant__robust____.html) rather than To Formant (burg)?

![image](https://user-images.githubusercontent.com/22280294/161680841-45808932-eb0b-416b-a6ff-92e14e1b38b6.png)

![image](https://user-images.githubusercontent.com/22280294/161680865-0d7d30b7-cbe1-4206-ba1b-434eac9acbd1.png)

**Comment by hykilpikonna** [comment]
Actually, setting time step to the default 0.01 makes the predictions more accurate.

**Comment by YannickJadoul** [comment]
Hi @hykilpikonna, that's strange. Parselmouth is using Praat's code, so for the same parameters, it should give the exact same results.

> What are some potential causes for this difference in accuracy with the same software?

So somehow, you're using a different parameters, I would hope? You you give me the values/screenshots from the parameters in the settings?

One other way to also compare is to just call "To Formant (burg)" in the main object window. This is the code that Parselmouth should be using, but sometimes the arguments to Praat's interactive Sound editor are slightly different.

> Is it possible that Praat is using [To Formant (robust)](https://www.fon.hum.uva.nl/praat/manual/Sound__To_Formant__robust____.html) rather than To Formant (burg)?

As far as I can tell, no. It seems that in "Formant > Advance formant settings...", the method "Burg" is selected by default, for me. Is that not the case for you?

**Comment by YannickJadoul** [comment]
Closing, after almost a year without replies to my questions.
