### ISSUE TITLE
Ltas class in parselmouth?

### ISSUE THREAD

**Issue by aebjorklund** [YannickJadoul/Parselmouth#79]
Is it possible to create objects of the Ltas class in parselmouth, [as there is natively in Praat?](https://www.fon.hum.uva.nl/praat/manual/Ltas.html) There doesn't seem to be any mention of Ltas in the documentation. Is it supported by parselmouth or something parselmouth might support in the future? Thanks!

**Comment by YannickJadoul** [comment]
@aebjorklund, there's indeed no Python class for it (yet), but you can do the following, with `parselmouth.praat.call`:

```pycon
>>> import parselmouth
>>> sound = parselmouth.Sound("the_north_wind_and_the_sun.wav")
>>> ltas = parselmouth.praat.call(sound, "To Ltas", 100)  
>>> type(ltas)
<class 'parselmouth.Data'>
>>> ltas.class_name
'Ltas'
>>> parselmouth.praat.call(ltas, "Get slope", 0.0, 1000, 1000, 4000, 'energy')
-19.468640854143416
```

I agree it's not as optimal in usage, but at least it's still possible to access the functionality this way

Check out https://parselmouth.readthedocs.io/en/stable/examples/pitch_manipulation.html and https://parselmouth.readthedocs.io/en/stable/api_reference.html#parselmouth.praat.call, as well, for more examples/explanation on using `parselmouth.praat.call`.

**Comment by aebjorklund** [comment]
Thank you!

**Comment by aebjorklund** [comment]
Thank you!
