### ISSUE TITLE
How to extract pitch value of all syllables in a audio file ?

### ISSUE THREAD

**Issue by code-010** [YannickJadoul/Parselmouth#80]
is there any function in parselmouth library which can extract the pitch value of each syllable in a audio file ?

**Comment by YannickJadoul** [comment]
I don't know if Praat (and thus Parselmouth) has a way of automatically detecting syllables (have a look around; this shouldn't be Parselmouth-specific, but just something for Praat). But of course, Parselmouth can extract pitch, just like Praat (see e.g. here: https://parselmouth.readthedocs.io/en/stable/examples/plotting.html).

**Comment by code-010** [comment]
Thank you.. I was able to extract the pitch value for all frame .

**Comment by YannickJadoul** [comment]
Great! Thank you for the update and closing of the issue, and good luck! :-)
