### ISSUE TITLE
Load Sound from memory?

### ISSUE THREAD

**Issue by alkemyst** [YannickJadoul/Parselmouth#83]
Hello,
  I would like to use the microphone input to run parselmouth, so I can get the sound in memory, as array or whatever else, but I cannot afford (timewise) writing to disk and then reading back.
  Is there any way to create a Sound from memory?

Thanks

**Comment by alkemyst** [comment]
I see that I can change the values directly via sound.values = [ ... ] once the sound object was build
But I would need an example on how to directly create a sound object from numeric samples

Thanks

**Comment by YannickJadoul** [comment]
Hi @alkemyst

Yes there is: you can create a `parselmouth.Sound` with a string (filename), but also with a list/array and sample rate. For example `parselmouth.Sound(np.sin(2 * np.pi * 440 * np.arange(48000) / 48000), sampling_frequency=48000)` should get you a nice mono sine wave of 1 second. For multiple channels, add multiple rows to the array.

(it's a bit hidden, but the constructor is listed here: https://parselmouth.readthedocs.io/en/stable/api_reference.html#parselmouth.Sound.__init__)

**Comment by YannickJadoul** [comment]
By the way, for simple questions (rather than actual bugs or big issues), you can also check out https://gitter.im/PraatParselmouth/Lobby, where you might get an even faster response :-)
