### ISSUE TITLE
How to get values for timestamps for pitch strength, MFCCs?

### ISSUE THREAD

**Issue by julian24bas** [YannickJadoul/Parselmouth#94]
Hi @YannickJadoul, I just used your solution form [here](https://github.com/YannickJadoul/Parselmouth/issues/67) to get the pitch frequency at a specific timestamp using ``pitch_object.get_value_at_time(t)``. However I also need the interpolated value for the pitch strength at the same timestamp but this method only gives me the frequency. For now I extracted the strength and corresponding timestamps following your [example](https://github.com/YannickJadoul/Parselmouth#readme) on how to create pitch plots and used scipy interpolation to do the job.
````
pitch = sound.to_pitch()
pitch_strength_y = pitch.selected_array["strength"]
pitch_x = pitch.xs()
pitch_strength_f = interp1d(x=pitch_x, y=pitch_strength_y, kind="linear", bounds_error=False)
pitch_strength_t = pitch_strength_f(t)
````
I have the same problem for getting MFCC values for specific timestamps. And "solved" it using the same scipy approach and your explanation for MFCCs [here](https://github.com/YannickJadoul/Parselmouth/issues/21).
````
mfcc = sound.to_mfcc(number_of_coefficients=2)
mfcc_coeff = mfcc.to_array()
mfcc_0_y = mfcc_coeff[1]
mfcc_1_y = mfcc_coeff[2]
mfcc_x = mfcc.xs()
mfcc_0_f = interp1d(x=mfcc_x, y=mfcc_0_y, kind="linear", bounds_error=False)
mfcc_1_f = interp1d(x=mfcc_x, y=mfcc_1_y, kind="linear", bounds_error=False)
mfcc_0_f(audio_x)
mfcc_1_f(audio_x)
````
This is ok but when testing and comparing it with the pitch frequency for some timestamps the results where not identical to the praat method ``pitch_object.get_value_at_time(t)``. In Addition this seems to be a more complicated solution than it should be. So I feel like I'm missing something. For the MFCC I do not know if this is a proper approach as I did not find anything on the Praat official website or the Parselmouth Docs on how to interpolate MFCCs, whereas for harmonicity or intensity it's mentioned that a cubic interpolation should be used and for pitch a linear interpolation.

Do you know how to get the pitch strength and MFCCs at a specific timestamp?

**Comment by YannickJadoul** [comment]
Hi @julian24bas. I've had a quick look on whether I stupidly forgot to implement this in Parselmouth, but I cannot find any sort of interpolation withing the Praat code or GUI either.

Actually, `Pitch_getStrengthAtTime` exists in the code, but is unused, and not exposed as Praat action in the GUI or scripts; so I'm assuming the Praat authors had a good reason for this? One of the reasons I can think of is that the "strength" is kind of a by-product of the pitch estimate method of a certain sample (auto- or cross-correlation of a sliding window), and that there's not really any sense interpolating?
Funnily enough though, Harmonicity actually takes these strengths, transforms them to dB, and then does let you interpolate them.

At any rate, as Praat does have a way of accessing this quantity in its GUI, Parselmouth does not have it, either. So you could access Harmonicity, or indeed, do the interpolation yourself.

Talking about the interpolation, to me SciPy seems to work, and to have rather small floating point rounding errors? A relative error of 10^-15 is +- what to expect when working with doubles, if I recall correctly.
```pycon
>>> import parselmouth
>>> import numpy as np
>>> import scipy.interpolate
>>> sound = parselmouth.Sound("the_north_wind_and_the_sun.wav")
>>> pitch = sound.to_pitch()
>>> pitch_track = pitch.selected_array['frequency']
>>> pitch_track[pitch_track == 0] = np.nan
>>> X = np.linspace(pitch.xmin, pitch.xmax, 10000)
>>> Y1 = np.array([pitch.get_value_at_time(x) for x in X])
>>> Y2 = scipy.interpolate.interp1d(pitch.xs(), pitch_track, kind='linear', bounds_error=False, fill_value=np.nan)(X)
>>> np.nanmax(np.abs(Y1 - Y2))
2.8421709430404007e-13
>>> np.nanmax(np.abs((Y1 - Y2) / Y1))
1.5378926465575117e-15
```

The one thing that is different between the two, though, you can see when plotting: in the case where you go from a missing value (i.e., unvoiced, for Pitch) to a non-NaN value, SciPy won't interpolate but Praat would interpolate halfway that interval between the two points.
![image](https://user-images.githubusercontent.com/8025744/209248116-df629d2c-3dfc-4061-88c9-d3114ebe351d.png)
![image](https://user-images.githubusercontent.com/8025744/209248131-3320c3f4-42c9-43cc-afbb-8e6a8320ac9e.png)

I don't know how different your test results were, but could this be the difference?

Yes, I agree it is a bit complicated, but given that Praat does not seem to provide this functionality, I would think it is indeed the easiest way to have SciPy do the job.

**Comment by YannickJadoul** [comment]
Second part of the answer, about MFCCs: I don't really know enough about them to say if MFCCs can be interpolated that easily. I actually thought that they weren't so continuous and could depend quite a bit on the window, but that's something you could easily test: try setting the `time_step`  to a smaller value, and compare the results to the interpolated ones of an MFCC analysis with a larger `time_step` to get an idea of how well the interpolation works? Alternatively, maybe there is some literature on interpolating MFCCs?

In general, as in the other issues you found, having predictable sample times for Praat's different analyses is a bit of a returning issue. Praat has made the choice to work with more intuitive window lengths and time steps in seconds, but this results in rounding to get to an integer number of samples in the actual signal processing. And this makes it harder to pick the parameters to get the wanted sample times and instead forces you to interpolate. I see that in some situations this is useful, while in others it makes things very annoying, and it can be an interesting discussion on what is the best way. But at any rate, it it nothing I can do much about in Parselmouth, as I'm mainly aiming to expose Praat's functionality to Python. Other implementations (like [librosa's](https://librosa.org/doc/main/generated/librosa.feature.mfcc.html#librosa.feature.mfcc)) might for example be easier to tweak to give the right number of MFCC samples (though of course, I don't want to scare you away from Parselmouth ;-) ).

Apologies. I know this is a bit of a non-answer, but I'm afraid there's not much more I know or can do. Do feel free to contact Praat / Paul Boersma to check if there's a better way to use Praat, for your use case. Very likely, I might know more about interpolating those MFCCs and why Praat does not allow you to interpolate Pitch strengths or MFCCs.
If Praat has a better way, I'm eager to learn about it, and then help you achieve the same with Parselmouth!!

**Comment by julian24bas** [comment]
Hi @YannickJadoul, thanks for the fast reply and your help! I really appreciate it!

For the pitch values converting the zeros to np.nan with ``pitch_track[pitch_track == 0] = np.nan`` solved it for me. I was using the array with zeros on the scipy interpolation which resulted in floats slightly above zero around timestamps with unvoiced areas. Converting those zeros to np.nan results in identical interpolation like the ``pitch.get_value_at_time(x)`` method wich returns ``np.nan`` for unvoiced areas.

For the MFCCs it sounds like a good idea to check the interpolation accuracy as you suggested. For now I'm using ``mfcc_0_f = interp1d(x=mfcc_x, y=mfcc_0_y, kind="nearest", bounds_error=False)`` to interpolate which uses nearest interpolation as the only ["literature"](https://musicinformationretrieval.com/mfcc.html) I found so far is doing it that way and this approach won't give me any weird results as no news values are calculated. As I'm also downsampling using interpolation, this will be more than good enough for my use case for now. But if I'm getting any news on this topic I'll let you know (:

**Comment by YannickJadoul** [comment]
@julian24bas Great to hear!

> For the pitch values converting the zeros to np.nan with `pitch_track[pitch_track == 0] = np.nan` solved it for me. I was using the array with zeros on the scipy interpolation which resulted in floats slightly above zero around timestamps with unvoiced areas. Converting those zeros to np.nan results in identical interpolation like the `pitch.get_value_at_time(x)` method wich returns `np.nan` for unvoiced areas.

Right, yes, sorry for the confusion there. There's always a tension between following Praat as closely as possible (as in this case, with the 0 for unvoiced but "undefined" when interpolating) and making things fit into Python!

> For the MFCCs it sounds like a good idea to check the interpolation accuracy as you suggested. For now I'm using `mfcc_0_f = interp1d(x=mfcc_x, y=mfcc_0_y, kind="nearest", bounds_error=False)` to interpolate which uses nearest interpolation as the only ["literature"](https://musicinformationretrieval.com/mfcc.html) I found so far is doing it that way and this approach won't give me any weird results as no news values are calculated. As I'm also downsampling using interpolation, this will be more than good enough for my use case for now. But if I'm getting any news on this topic I'll let you know (:

Right, that makes sense, indeed. Especially when downsampling and tweaking the step size, it should also give you some sort of upper bound on the difference in sample time :-)
If you do find anything, I'm always curious, though, so please do! Thanks!
